### ISSUE TITLE
share option not working

### ISSUE THREAD

**Issue by msusta** [Answers4AWS/distami#10]
There is most likely a bug in the implementation of sharing in CLI handler.

```
def copy(param_array):
---redacted---
    copied_ami_id = distami.copy_to_region(to_region)
    ami_cp = Distami(copied_ami_id, to_region)
---redacted---
    if args.accounts:
        distami.share_ami_with_accounts(args.accounts)
```
Here the copy() copies the original AMI to new AMI with copy_to_region and even creates a new Distami with name ami_cp for the new AMI ID, however the list line references again the distami object tied to original AMI ID. What's more there is no reference to sharing the snapshot.

Guess this should look like part about sharing in run() which handles the original AMI.
```
        if args.accounts:
            account_ids = args.accounts.split(',')
            distami.share_ami_with_accounts(account_ids)
            distami.share_snapshot_with_accounts(account_ids)
```

Will submit a patch later.

**Comment by pas256** [comment]
Thanks. Sorry I missed this eariler
